### PR TITLE
Update scrutinizer

### PR DESCRIPTION
**Pull request by danepowell**
Builds are failing and I'm wondering if updating PHP / Composer will help.

### CODE REVIEW

**Comment by danepowell** [comment]
Updating PHP didn't help but I think logging into Scrutinizer so it could use my GitHub token to bypass rate limits may have done the trick.

**Comment by danepowell** [comment]
@typhonius can you make me an admin in Scrutinizer so I can figure out why it's failing? It's using an ancient version of PHPCodeSniffer for some reason.

Or else can we just disable Scrutinizer? I don't know what value it provides over what we could already do in GitHub Actions with PHPCS, PHPStan, etc

**Comment by typhonius** [comment]
> [danepowell](/danepowell)



> @typhonius can you make me an admin in Scrutinizer so I can figure out why it's failing? It's using an ancient version of PHPCodeSniffer for some reason.
> 
> Or else can we just disable Scrutinizer? I don't know what value it provides over what we could already do in GitHub Actions with PHPCS, PHPStan, etc

Have added you as an admin in scrutinizer. I don't think it's super necessary anymore to be honest. I think I added it in the first place because it was nice to have a badge on the readme that was green.

**Comment by danepowell** [comment]
No matter what I tried Scrutinizer kept trying to install an ancient version of PHPCS which broke in PHP 8.2

Finally in the UI I found an undocumented option on [the "open source analysis tools config" tab](https://scrutinizer-ci.com/g/typhonius/acquia-php-sdk-v2/settings/build-config) to upgrade PHPCS and that fixed it.

I'll let it slide this time but if it keeps giving us grief I vote to disable scrutinizer.

**Pull request merged**
