### PR TITLE
Adds the ability to download DBs via the API.

### PR DESCRIPTION
**Pull request by typhonius**

### CODE REVIEW

**Comment by typhonius** [comment]
A consumer would approach this in the following way:

```
$backup = new DatabaseBackups($client);
$download = $backup->download('UUID', 'default', '1');
$download->rewind();
$contents = $download->getContents();

$tmpFile = tempnam(sys_get_temp_dir(), 'database') . '.sql.gz';
file_put_contents($tmpFile, $aliases, LOCK_EX);
```

**Comment by weitzman** [comment]
I'm seeing a curl error shortly after the the database starts downloading. Its working for you? Is your DB large? Some relevant discussion of this error https://github.com/guzzle/guzzle/issues/1600 and https://stackoverflow.com/questions/1759956/curl-error-18-transfer-closed-with-outstanding-read-data-remaining/1847591

```
cURL error 18: transfer closed with 1755079179 bytes remaining to read (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```

**Comment by typhonius** [comment]
With further investigation, the above issue looks like it was limited to a single subscription so this PR should work.

**Comment by weitzman** [comment]
Yes, PR likely works. My subscription still doesn't work sadly. The engineers are "investigating"

**Comment by typhonius** [comment]
Merged in 2afdfb3bf6c6bc00e5aad2e1918b68cc63d1caa7

**Pull request closed without merging**
