### PR TITLE
Fix #218: webmozart/path-util is abandoned

### LINKED ISSUE #218: webmozart/path-util is abandoned
**Describe the bug**
Installing via Composer throws a warning:
> Package webmozart/path-util is abandoned, you should avoid using it. Use symfony/filesystem instead.

We should replace that package

### PR DESCRIPTION
**Pull request by danepowell**
Fix #218 by replacing webmozart/path-util with symfony/filesystem (Path components were migrated into the 5.4 filesystem release)

This breaks compatibility with Symfony 4. @typhonius is that something you'd like to avoid? If so this gets a little more complicated, we may need a new major release branch or something.

This also removes support for PHP 7.3, which isn't strictly necessary but helps in fixing tests and Composer dependencies.

### CODE REVIEW

**Comment by grasmash** [comment]
Looks good to me.

**Comment by typhonius** [comment]
> This breaks compatibility with Symfony 4. @typhonius is that something you'd like to avoid? If so this gets a little more complicated, we may need a new major release branch or something.

I feel like if we're removing compatibility with a PHP version and Symfony 4, it might be simpler to tag this as a new release. I know it's not specifically semver, but maybe we just use a new minor version for this e.g. 2.1 since I've pretty much added everything as a patch release to this point and only created new major versions for entire rewrites.

That way it keeps things simple for the majority of users who'll be installing this with the recommended `^2` version and if anyone has compatibility issues they can stay on 2.0.

**Comment by danepowell** [comment]
> I feel like if we're removing compatibility with a PHP version and Symfony 4, it might be simpler to tag this as a new minor release.

Makes sense.

FWIW, we are not the only ones experiencing this pain. If we're very lucky, Drush might take over path-util or come up with a more elegant solution: https://github.com/drush-ops/drush/issues/4935

**Comment by danepowell** [comment]
Removing Symfony 4 and PHP 7.3 are moot issues now that that's already happened in #225, so I think this is good to go.

**Pull request merged**
