### PR TITLE
Fix #283: Support non-production Accounts API

### LINKED ISSUE #283: Cannot use non-production endpoints
https://github.com/typhonius/acquia-php-sdk-v2/pull/137 was supposed to allow testing against non-production Cloud API endpoints, but I suspect it never worked as intended because the Connector OAuth client will still use the production Accounts endpoint, making it impossible to authenticate against the stage API.

### PR DESCRIPTION
**Pull request by danepowell**
Fix #283

### CODE REVIEW

**Comment by danepowell** [comment]
@typhonius your Coveralls token appears to be broken yet again, could you please help? 😄

**Comment by typhonius** [comment]
> @typhonius your Coveralls token appears to be broken yet again, could you please help? 😄

👀

**Comment by typhonius** [comment]
Back to you @danepowell - github actions for codecov needed an update to a supported version (#286)

**Comment by danepowell** [comment]
Ugh... looks like the the codecov failures are basically an outage due to rate limiting and not something we can work around (other than to disable codecov entirely): https://github.com/codecov/codecov-action/issues/837

I'll retry the action a few times and see what happens

**Pull request merged**
