### PR TITLE
Adds account method for getting details about the user's account.

### LINKED ISSUE #20: Add account method
It would be nice if there was a way to call the `account` endpoint. It doesn't seem like this is possible now. This could be a dedicated account method, or a method that lets you call arbitrary endpoints that might not yet be supported by this package.

My use case isn't really to get account info, but to check that authentication was successful. I've been told that calling `account` is significantly less expensive than calling other methods like `applications`.

### PR DESCRIPTION
**Pull request by typhonius**

### CODE REVIEW

**Comment by typhonius** [comment]
This will fix #20

**Comment by danepowell** [comment]
Thanks, I'm testing this over in https://github.com/acquia/blt/issues/3742 but looks good so far

**Comment by danepowell** [comment]
Yep this works for us!

**Comment by danepowell** [comment]
@typhonius do you want any help fixing the test, or with anything else before merging?

I've heard from the Cloud team that the docs should be updated imminently to include created_at.

**Comment by typhonius** [comment]
Sorry, I'd forgotten about this. It's merged in now but please let me know if it would benefit BLT for me to cut a new release tag for this (and if there are any concerns/caveats that should be addressed prior to doing so).

**Comment by danepowell** [comment]
A new release would be much appreciated. I'm not aware of any issues that would block a release.

**Comment by typhonius** [comment]
1.0.4 has been created :)

**Pull request merged**
