### PR TITLE
Loosen HMAC constraint

### PR DESCRIPTION
**Pull request by balsama**
Is it possible to use acquia/http-hmac-php: 2.x with this package? I'm not familiar with either, but I understand that some downstream dependencies have conflicts and thought I would ask :)

### CODE REVIEW

**Comment by typhonius** [comment]
Unfortunately I'm not too familiar with acquia/http-hmac-php either. I'm using guidance from the repo README to influence which version of the package is used here. My concern would be that the 2.x version is over 2 years old so there could be other issues at stake.

Could it be the case that deps to http-hmac-php 3.x may be relaxed?

@itafroma perhaps you could also please provide some guidance?

**Comment by itafroma** [comment]
There are two versions of the HTTP HMAC spec: acquia/http-http-hmac <3.0.0 only supports v1 of the spec, while >=3.0.0 only supports v2. All Acquia APis that use the spec use v2, so 3.x is required.

We may be able to adjust the constraints on the library: if you can file a ticket with the dependency issues we're having, we can look into it!

**Comment by scor** [comment]
@itafroma The Content Hub PHP client still use HMACv1 (2.x branch of the library), and that's where the problem comes from. We're in the middle of upgrading to HMACv2 (3.x branch) but it's going to take several weeks once we release for all customers to move to 100% HMACv2, so in the meantime it would make sense I think to allow both the 2.x and 3.x branch to be used.

**Comment by scor** [comment]
We just released drupal/acquia_contenthub 8.x-1.24 and acquia/content-hub-php 1.3.0 which no longer rely on acquia/http-hmac-php 2.x so we're good to close this issue.

**Pull request closed without merging**
