### PR TITLE
Set exception response

### PR DESCRIPTION
**Pull request by grasmash**
This allows an implementing tool to catch the ApiErrorException and access the API response body object directly. Required to resolve https://github.com/acquia/cli/issues/159.

### CODE REVIEW

**Comment by grasmash** [comment]
This allows an implementing tool to catch the ApiErrorException and access the API response body object directly. Required to resolve https://github.com/acquia/cli/issues/159.

**Comment by grasmash** [comment]
This is only reducing coverage because there are now more lines of code in total. No new uncovered lines have been added.

**Comment by teamshape** [comment]
Thanks for this, I wasn't sure how to handle exceptions best and this looks like it will serve dependent libraries better.

**Comment by typhonius** [comment]
Thanks for this, I wasn't sure how to handle exceptions best and this looks like it will serve dependent libraries better.

**Pull request merged**
