### PR TITLE
Updating form_params to json

### LINKED ISSUE #81: Using x-www-form-urlencoded is untyped and causes issues with api backend validation
**Describe the bug**
As an example, the `environment->update()` method should take values like `['memory_limit' => 192]`, however, the API returns: 

```
PHP Fatal error:  Uncaught AcquiaCloudApi\Exception\ApiErrorException: [0]: 192 is not a valid memory limit. It should be an integer.
```

This is because `x-www-form-urlencoded` is not typed and everything comes through as a string. I am trying to track down any documentation on this on Acquia's side, but confirmed with the API team last year about boolean values.

**To Reproduce**
```
$environment = new Environments($client);
$environmentUuid = '<REDACTED>';
$config = [
  'memory_limit' => 152,
];

$environment->update($environmentUuid, $config);
```

**Expected behavior**
I expect that it succeeds.

### PR DESCRIPTION
**Pull request by eporama**
This is a PR to fix #81

### CODE REVIEW

**Comment by typhonius** [comment]
Thanks @eporama for the deep dive into this. One question - do you think that based on this behaviour we need some kind of test for encoding and content-type or would this be covered by Guzzle's tests?

**Comment by eporama** [comment]
I don't know that we would… I'm not sure that it's any more testable than using `form_params` was… but I could be wrong on that. I'm learning a lot about these things today…

**Comment by typhonius** [comment]
Thanks for that, I'll have a peek over the next couple of days to see if I can add anything else here - if not I'll merge.

**Comment by typhonius** [comment]
Looking at this again, we already check that `json` (not `form_params`) are within the options array passed to Guzzle so I'm happy to not include any additional tests (since it should be covered in Guzzle).

**Pull request merged**
